### ISSUE TITLE
Add option to publish docker images in branch in CI

### ISSUE THREAD

**Issue by sindrig** [island-is/island.is#1179]
After discussion with @darrikonn we decided a label on a PR would be best.

Adding a label to a PR: ```jq -n '{"labels": ["ci"]}' -cM | gh api --silent /repos/:owner/:repo/issues/1071/labels --input -```

**Comment by sindrig** [comment]
Since it's easier to use tags to trigger workflows I decided on tagging instead
```
on:
  push:
    branches:
      - 'master'
      - 'release/**'
      - 'hotfix/**'
    paths-ignore:
      - '**/*.md'
    tags:
      - docker-build-*
```
